version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: simple_bank
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://root:secret@db:5432/simple_bank?sslmode=disable
    depends_on:
      - db
    links:
      - db
