name: ci-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21.2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd tutorial-simple-bank
          go mod download

      - name: Install Golang Migrate
        run: |
          MIGRATE_VERSION=v4.17.0
          curl -L -o migrate.tar.gz https://github.com/golang-migrate/migrate/releases/download/${MIGRATE_VERSION}/migrate.linux-amd64.tar.gz
          tar -xzf migrate.tar.gz
          ls -al # List files to debug
          sudo mv migrate /usr/local/bin/migrate

      - name: Verify Golang Migrate Installation
        run: migrate -version

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
